# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 제주씨 Hi~
email: callin2@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  이것은 본격적인 제주살이 블로그!!!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: callin2
github_username:  callin2

# Build settings
markdown: kramdown


gems: ['jekyll-plantuml']